<?php
return array (
  'version' => 
  array (
    'app' => 
    array (
      'default' => 
      array (
        0 => '001_create_divisions',
        1 => '002_create_events',
        2 => '003_create_event_details',
        3 => '004_create_users',
        4 => '005_create_activities',
        5 => '006_add_government_code_to_divisions',
        6 => '007_create_reference_dates',
        7 => '008_add_no_to_event_details',
        8 => '009_add_fullname_to_divisions',
        9 => '010_update_fullname_in_divisions',
        10 => '011_add_geoshape_to_event_details',
        11 => '012_add_is_refer_to_event_details',
        12 => '013_add_belongs_to_divisions',
        13 => '014_add_show_postfix_to_divisions',
        14 => '015_add_display_order_to_divisions',
        15 => '016_add_is_unfinished_to_divisions',
        16 => '017_add_comment_to_events',
        17 => '018_add_sort_columns_to_divisions',
        18 => '019_update_sort_columns_in_divisions',
        19 => '020_modify_belongs_in_divisions',
        20 => '021_add_top_parent_division_id_to_divisions',
        21 => '022_update_top_parent_id_to_divisions',
        22 => '023_rename_suffix_in_divisions',
        23 => '024_create_pages',
        24 => '025_rename_title_in_events',
        25 => '026_add_newcomment_to_events',
        26 => '027_update_newcomment_in_events',
        27 => '028_delete_comment_from_events',
        28 => '029_rename_comment_in_events',
        29 => '030_rename_division_result_to_result_in_eveit_details',
        30 => '031_add_order_to_event_details',
        31 => '032_update_order_in_event_details',
        32 => '033_delete_no_from_event_details',
        33 => '034_add_new_geoshape_and_new_is_refer_to_event_details',
        34 => '035_update_new_geoshape_and_new_is_refer_in_event_details',
        35 => '036_delete_geoshape_and_is_refer_from_event_details',
        36 => '037_rename_new_geoshape_and_new_is_refer_in_event_details',
        37 => '038_add_identifier_to_divisions',
        38 => '039_update_identifier_in_divisions',
        39 => '040_delete_identify_from_divisions',
        40 => '041_add_new_fullname_and_new_fullname_kana_to_divisions',
        41 => '042_update_new_fullname_and_new_fullname_kana_in_divisions',
        42 => '043_delete_fullname_and_fullname_kana_divisions',
        43 => '044_rename_new_fullname_and_new_fullname_kana_in_divisions',
        44 => '045_add_path_and_path_kana_to_divisions',
        45 => '046_update_path_and_path_kana_in_divisions',
        46 => '047_add_new_top_parent_division_id_to_divisions',
        47 => '048_update_new_top_parent_division_id_in_divisions',
        48 => '049_delete_top_parent_division_id_from_divisions',
        49 => '050_rename_new_top_parent_division_id_in_divisions',
      ),
    ),
    'module' => 
    array (
    ),
    'package' => 
    array (
    ),
  ),
  'folder' => 'migrations/',
  'table' => 'migration',
);
